application:
            name: HeadHuntApp-001
            execution_profile: dev
            datasource: 
                       dburl: localhost
                       #port: 8087
                       database_name: mydb
                       # connectionstring: jdbc:h2:mem:mydb
                       connectionstring: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
                       # connectionstring: jdbc:h2:~/mydb
                       user_name: sa
                       password: 
                       hibernate.dialect : org.hibernate.dialect.H2Dialect
                       hibernate.show_sql : true
                       logging.org.hibernate.tool.hbm2ddl : DEBUG
                       logging.org.hibernate.SQL : DEBUG
                       hibernate.hbm2ddl.auto : create-drop
                       driver.classname : org.h2.Driver
                       hibernate.temp.use_jdbc_metadata_defaults : false
spring.h2.console.enabled: true
spring.h2.console.path: /h2
                       
                       